### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by delokman** [lionvoom/WeAppCrack#1]
i started to researching about about miniapp
i need your contact to chat directly

thanks a lot

**Comment by lionvoom** [comment]
Sorry, I just read your message, please email me. 🤝

**Comment by rmros** [comment]
share your mail or your dingtalk

**Comment by lionvoom** [comment]
My git home has a public email address : lionvoom@gmail.com

**Comment by rmros** [comment]
> My git home has a public email address : [lionvoom@gmail.com](mailto:lionvoom@gmail.com)

i sent to you email,
its my dingtalk:rostami
please message
